@{
#AliasesToExport=""
Author="Joel Bennett"
#CmdletsToExport=""
CompanyName="http://HuddledMasses.org"
Copyright="© 2009, Joel Bennett, released under the Ms-PL"
Description="A Show-UI module for charting and graphing"
CLRVersion="2.0"
#FileList=""
#FunctionsToExport=""
GUID="38913b49-7eb7-427a-bccd-4cb6760c0971"
ModuleToProcess="PowerChart.psm1"
ModuleVersion="0.0.1.0"
PowerShellVersion="2.0"
#PrivateData=""
RequiredModules="ShowUI"
}
